import { Base, Card, CurrentEffect, DiscardedCard, GamePhase, Leader, PlayerId, Resource } from "./core-models";
import { TriggerEntry } from "./trigger-types";
import { Unit } from "./unit";

/** How a card entered play this phase. */
export type EntryReason =
  | "played"          // paid cost from hand
  | "deployed"        // leader flipped from Leader zone
  | "returned-to-play" // bounced back, resurrected, or similar
  | "token-created"   // token unit generated by an ability
  | "other";

/** How a card left play this phase. */
export type ExitReason =
  | "defeated"          // HP reached 0 or "defeat" effect
  | "captured"          // taken captive by another unit (non-tokens only)
  | "token-defeated"    // captured token — tokens cannot be held captive
  | "returned-to-hand"  // bounce (e.g. "return to owner's hand")
  | "returned-to-deck"  // shuffled back into deck
  | "other";

export interface GameState {
  activePlayer: PlayerId;
  defeatedPlayers: PlayerId[];
  gamePhase: GamePhase;
  player1: {
    base: Base;
    leader: Leader;
    spaceArena: Unit[];
    groundArena: Unit[];
    resources: Resource[];
    discard: DiscardedCard[];
    deck: Card[];
    hand: Card[];
    supplemental: {
      forceToken?: boolean;
      creditTokens?: number;
    }
  };
  player2: {
    base: Base;
    leader: Leader;
    spaceArena: Unit[];
    groundArena: Unit[];
    resources: Resource[];
    discard: DiscardedCard[];
    deck: Card[];
    hand: Card[];
    supplemental: {
      forceToken?: boolean;
      creditTokens?: number;
    }
  };
  currentEffects: CurrentEffect[];
  currentRound: number;
  initiativePlayer: PlayerId;
  initiativeClaimed: boolean;
  roundState: {
    /** Cards that were played as a game action this phase (paid cost from hand). */
    cardsPlayedThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string }[];
    /** All cards that entered play this phase, by any means. */
    cardsEnteredPlayThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string; reason: EntryReason }[];
    /** All cards that left play this phase, by any means (defeats, captures, bounces, etc). */
    cardsLeftPlayThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string; reason: ExitReason }[];
    unitsAttackedThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string }[];
  };
  triggerBag: TriggerEntry[];
}

export interface Game {
  currentGameState: GameState;
  gameStateHistory: GameState[];
  gameLog: string[];
}