import type { GameState } from "@/lib/engine/game";
import { GameStateBuilder } from "@/server/engine/game-state-builder";

export const sabineWrenCadBaneSimplePuzzleState: GameState = new GameStateBuilder()
  .WithActivePlayer(1)
  .WithGamePhase("ActionPhase")
  .MyBase("SOR_022", 23)
  .MyLeader("SOR_014")
  .TheirBase("SOR_025", 11)
  .TheirLeader("SHD_014", true, false, true)
  .FillResourcesForPlayer(1, "SHD_160", 8)
  .WithCardInHandForPlayer(1, "JTL_153")
  .WithCardInHandForPlayer(1, "SOR_168")
  .WithCardInHandForPlayer(1, "SOR_103")
  .WithCardInHandForPlayer(1, "SOR_141")
  .WithCardInHandForPlayer(1, "SOR_150")
  .WithGroundUnitForPlayer(1, "SOR_145")
  .WithGroundUnitForPlayer(1, "SHD_160")
  .WithGroundUnitForPlayer(2, "SOR_211", false)
  .WithGroundUnitForPlayer(2, "TWI_187", false)
  .WithCurrentRoundBeing(7)
  .WithInitiativePlayerBeing(2)
  .WithInitiativeClaimed()
  .Build()
;

export const bobaDaimyoLeiaAdelphiPuzzleState: GameState = new GameStateBuilder()
  .WithActivePlayer(1)
  .WithGamePhase("ActionPhase")
  .WithInitiativePlayerBeing(2)
  .WithInitiativeClaimed()
  .MyBase("SOR_022", 24)
  .MyLeader("SHD_008", true, false, true)
  .WithGroundUnitForPlayer(1, "SOR_098", false)
  .WithSpaceUnitForPlayer(1, "SHD_101")
  .FillResourcesForPlayer(1, "SOR_095", 8)
  .WithCardInHandForPlayer(1, "SOR_094")
  .WithCardInHandForPlayer(1, "SOR_103")
  .WithCardInHandForPlayer(1, "SOR_095")
  .WithCardInHandForPlayer(1, "SOR_106")
  .WithCardInHandForPlayer(1, "SOR_127")
  .WithCardInHandForPlayer(1, "SHD_132")
  .TheirBase("SOR_026", 22)
  .TheirLeader("SOR_009", true, false, true)
  .WithGroundUnitForPlayer(2, "SOR_145", false, 3)
  .FillResourcesForPlayer(2, "SOR_095", 6)
  .Build()
;
