export const Cards = {
  bases: {
    common: {
      blue30HP: "SOR_020",
      green30HP: "SOR_023",
      red30HP: "SOR_026",
      yellow30HP: "SOR_029",
      blue28HPForce: "LOF_020",
      green28HPForce: "LOF_023",
      red28HPForce: "LOF_026",
      yellow28HPForce: "LOF_029",
      blue27HPSplash: "LAW_020",
      green27HPSplash: "LAW_022",
      red27HPSplash: "LAW_025",
      yellow27HPSplash: "LAW_028",
    },
    sor: {
      securityComplex: "SOR_019",
      energyConversionLab: "SOR_022",
      tarkintown: "SOR_025",
      jedhaCity: "SOR_028",
    },
    twi: {
      pauCity: "TWI_019",
      droidManufactory: "TWI_022",
      shadowCollectiveCamp: "TWI_025",
      petranakiArena: "TWI_028",
    },
    jtl: {
      colossus: "JTL_021",
      dataVault: "JTL_024",
      thermalOscillator: "JTL_025",
      nabatVillage: "JTL_028",
      lakeCountry: "JTL_031",
    },
    lof: {
      vergenceTemple: "LOF_019",
      mysticMonastery: "LOF_022",
      templeOfDestruction: "LOF_025",
      tombOfEilram: "LOF_028",
    },
    law: {
      allianceOutpost: "LAW_019",
      greatPitOfCarkoon: "LAW_023",
      shipbreakingYard: "LAW_026",
      citadelResearchCenter: "LAW_029",
    }
  },
  leaders: {
    sor: {
      directorKrennic: "SOR_001",
      idenVersio: "SOR_002",
      chewbacca: "SOR_003",
      chirrutImwe: "SOR_004",
      lukeSkywalker: "SOR_005",
      emperorPalpatine: "SOR_006",
      grandMoffTarkin: "SOR_007",
      heraSyndulla: "SOR_008",
      leiaOrgana: "SOR_009",
      darthVader: "SOR_010",
      grandInquisitor: "SOR_011",
      ig88: "SOR_012",
      cassianAndor: "SOR_013",
      sabineWren: "SOR_014",
      bobaFett: "SOR_015",
      grandAdmiralThrawn: "SOR_016",
      hanSolo: "SOR_017",
      jynErso: "SOR_018",
    },
    shd: {
      garSaxon: "SHD_001",
      qira: "SHD_002",
      finn: "SHD_003",
      rey: "SHD_004",
      hondoOhnaka: "SHD_005",
      jabbaTheHutt: "SHD_006",
      moffGideon: "SHD_007",
      bobaFett: "SHD_008",
      hunter: "SHD_009",
      bossk: "SHD_010",
      kyloRen: "SHD_011",
      boKatanKryze: "SHD_012",
      hanSolo: "SHD_013",
      cadBane: "SHD_014",
      doctorAphra: "SHD_015",
      fennecShand: "SHD_016",
      landoCalrissian: "SHD_017",
      theMandalorian: "SHD_018",
    },
    twi: {
      nalaSe: "TWI_001",
      nuteGunray: "TWI_002",
      obiWanKenobi: "TWI_003",
      yoda: "TWI_004",
      countDooku: "TWI_005",
      watTambor: "TWI_006",
      captainRex: "TWI_007",
      padmeAmidala: "TWI_008",
      maul: "TWI_009",
      preVizsla: "TWI_010",
      ahsokaTano: "TWI_011",
      anakinSkywalker: "TWI_012",
      maceWindu: "TWI_013",
      asajjVentress: "TWI_014",
      generalGrievous: "TWI_015",
      jangoFett: "TWI_016",
      chancellorPalpatine: "TWI_017",
      quinlanVos: "TWI_018",
    },
    jtl: {
      asajjVentress: "JTL_001",
      grandAdmiralThrawn: "JTL_002",
      landoCalrissian: "JTL_003",
      roseTico: "JTL_004",
      admiralPiett: "JTL_005",
      darthVader: "JTL_006",
      admiralHoldo: "JTL_007",
      wedgeAntilles: "JTL_008",
      bobaFett: "JTL_009",
      captainPhasma: "JTL_010",
      majorVonreg: "JTL_011",
      lukeSkywalker: "JTL_012",
      poeDameron: "JTL_013",
      admiralTrench: "JTL_014",
      rioDurant: "JTL_015",
      admiralAckbar: "JTL_016",
      hanSolo: "JTL_017",
      kazudaXiono: "JTL_018",
    },
    lof: {
      kyloRen: "LOF_001",
      motherTalzin: "LOF_002",
      ahsokaTano: "LOF_003",
      kananJarrus: "LOF_004",
      morganElsbeth: "LOF_005",
      supremeLeaderSnoke: "LOF_006",
      avarKriss: "LOF_007",
      obiWanKenobi: "LOF_008",
      darthMaul: "LOF_009",
      thirdSister: "LOF_010",
      kitFisto: "LOF_011",
      rey: "LOF_012",
      barrissOffee: "LOF_013",
      grandInquisitor: "LOF_014",
      calKestis: "LOF_015",
      quiGonJinn: "LOF_016",
      darthRevan: "LOF_017",
      anakinSkywalker: "LOF_018",
    },
    law: {
      sawGerrera: "LAW_001",
      tobiasBeckett: "LAW_002",
      agentKallus: "LAW_003",
      aurraSing: "LAW_004",
      jynErso: "LAW_005",
      velSartha: "LAW_006",
      bobaFett: "LAW_007",
      directorKrennic: "LAW_008",
      heraSyndulla: "LAW_009",
      leiaOrgana: "LAW_010",
      darthVader: "LAW_011",
      sebulba: "LAW_012",
      chewbacca: "LAW_013",
      enfysNest: "LAW_014",
      jabbaTheHutt: "LAW_015",
      theClient: "LAW_016",
      hanSolo: "LAW_017",
      landoCalrissian: "LAW_018",
    },
    sec: {
      chancellorPalpatine: "SEC_001",
      jabbaTheHutt: "SEC_002",
      lamaSu: "SEC_003",
      leiaOrgana: "SEC_004",
      satineKryze: "SEC_005",
      colonelYularen: "SEC_006",
      drydenVos: "SEC_007",
      bailOrgana: "SEC_008",
      monMothma: "SEC_009",
      dedraMeero: "SEC_010",
      governorPryce: "SEC_011",
      cassianAndor: "SEC_012",
      luthenRael: "SEC_013",
      slyMoore: "SEC_014",
      c3po: "SEC_015",
      padmeAmidala: "SEC_016",
      sabe: "SEC_017",
      dj: "SEC_018",
    },
    ibh: {
      leiaOrgana: "IBH_001",
      darthVader: "IBH_053",
    },
    ts26: {
      countDooku: "TS26_001",
      anakinSkywalker: "TS26_002",
      maul: "TS26_003",
      padmeAmidala: "TS26_004",
      savageOpress: "TS26_005",
      rex: "TS26_006",
      asajjVentress: "TS26_007",
      ahsokaTano: "TS26_008",
    },
  },
  units: {
    token: {
      battleDroid: "TWI_T01",
      cloneTrooper: "TWI_T02",
      tieFighter: "JTL_T01",
      xWing: "JTL_T02",
      spy: "SEC_T01",
    },
    sor: {
      wingLeader: "SOR_241",
      systemPatrolCraft: "SOR_066",
      battlefieldMarine: "SOR_095",
      echoBaseDefender: "SOR_098",
      brightHope: "SOR_099",
      superlaserTechnician: "SOR_083",
      fightersForFreedom: "SOR_143",
      k2so: "SOR_145",
      wampa: "SOR_164",
      craftySmuggler: "SOR_207",
      syndicateLackeys: "SOR_213",
      rebelPathfinder: "SOR_239",
      gamorreanGuards: "SOR_211",
      emperorPalpatine: "SOR_135",
      vanguardInfantry: "SOR_108",
      generalTagge: "SOR_080",
      deathTrooper: "SOR_033",
      delMeeko: "SOR_034",
      darthVader: "SOR_087",
      cellBlockGuard: "SOR_229",
      atAtSuppressor: "SOR_039",
      surgicalDroid: "SOR_059",
      distantPatroller: "SOR_060",
      patrollingVWing: "SOR_111",
      imperialInterceptor: "SOR_132",
      ruthlessRaider: "SOR_134",
      starWingScout: "SOR_163",
      leiaOrgana: "SOR_189",
      cantinaBouncer: "SOR_202",
      miningGuildTIE: "SOR_206",
      fleetLieutenant: "SOR_240",
    },
    shd: {
      generalTagge: "SHD_081",
      sundariPeaceKeeper: "SHD_098",
      recklessGunslinger: "SHD_160",
      fourLom: "SHD_188",
      zuckuss: "SHD_190",
      hylobonEnforcer: "SHD_027",
      tech: "SHD_248",
      warbirdStowaway: "SHD_086",
      chewbaccaPykesbane: "SHD_050",
      sugi: "SHD_052",
      djBlatantThief: "SHD_213",
      theMandalorian: "SHD_049",
      tobiasBeckett: "SHD_217",
      supercommandoSquad: "SHD_034",
      followerOfTheWay: "SHD_056",
    },
    jtl: {
      kijimiPatrollers: "JTL_082",
      l337: "JTL_049",
      lukeSkywalker: "JTL_094",
      blueLeader: "JTL_096",
      rebelliousHammerhead: "JTL_153",
      snapWexley: "JTL_098",
      r2d2: "JTL_245",
      millenniumFalcon: "JTL_249",
    },
    lof: {
      kelleranBeq: "LOF_100",
      gungi: "LOF_093",
      strikeship: "LOF_131",
      witchOfTheMist: "LOF_154",
      theLegacyRun: "LOF_213",
      sandtrooperCavalry: "LOF_232",
    },
    twi: {
      infiltratingDemolisher: "TWI_182",
      admiralTrench: "TWI_086",
      sanHill: "TWI_186",
      r2d2FullOfSolutions: "TWI_193",
    },
    sec: {
      cadBane: "SEC_034",
      chancellorPalpatine: "SEC_082",
      isbShuttle: "SEC_083",
      viceAdmiralRampart: "SEC_085",
    },
  },
  upgrades: {
    token: {
      experience: "SOR_T01",
      shield: "SOR_T02",
    },
    sor: {
      entrenched: "SOR_072",
      protector: "SOR_057",
      academyTraining: "SOR_120",
      traitorous: "SOR_122",
      hardpointHeavyBlaster: "SOR_121",
    },
    shd: {
      legalAuthority: "SHD_124",
      publicEnemy: "SHD_068",
      hotshotBlaster: "SHD_174",
      theDarksaber: "SHD_126",
      mandalorianArmor: "SHD_073",
      vambraceFlamethrower: "SHD_177",
    },
    lof: {
      bolsteredEndurance: "LOF_074",
      constructedLightsaber: "LOF_261",
    },
  },
  events: {
    shd: {
      timelyIntervention: "SHD_129",
      chooseSides: "SHD_132",
    },
    sor: {
      momentOfPeace: "SOR_073",
      rebelAssault: "SOR_103",
      strikeTrue: "SOR_127",
      heroicSacrifice: "SOR_150",
      waylay: "SOR_222",
      changeOfHeart: "SOR_224",
      confiscate: "SOR_251",
      attackPatternDelta: "SOR_106",
      takedown: "SOR_077",
      overwhelmingBarrage: "SOR_092",
      vanquish: "SOR_078",
      recruit: "SOR_123",
      uWingReinforcement: "SOR_104",
      makeAnOpening: "SOR_076",
      tacticalAdvantage: "SOR_124",
      karabast: "SOR_151",
      keepFighting: "SOR_169",
      powerFailure: "SOR_170",
      missionBriefing: "SOR_171",
      openFire: "SOR_172",
      bombingRun: "SOR_173",
      disarm: "SOR_216",
      surpriseStrike: "SOR_220",
      outmaneuver: "SOR_221",
    },
    twi: {
      vanquish: "TWI_077",
      droidDeployment: "TWI_237",
      dropIn: "TWI_251",
      takeCaptive: "TWI_128",
    },
    jtl: {
      torpedoBarrage: "JTL_234",
      dedicatedWingmen: "JTL_254",
      unityOfPurpose: "JTL_106",
    },
    sec: {
      iAmTheSenate: "SEC_092",
    },
  },
}
