export const Cards = {
  bases: {
    common: {
      blue30HP: "SOR_020",
      green30HP: "SOR_023",
      red30HP: "SOR_026",
      yellow30HP: "SOR_029",
      blue28HPForce: "LOF_020",
      green28HPForce: "LOF_023",
      red28HPForce: "LOF_026",
      yellow28HPForce: "LOF_029",
      blue27HPSplash: "LAW_020",
      green27HPSplash: "LAW_022",
      red27HPSplash: "LAW_025",
      yellow27HPSplash: "LAW_028",
    },
    sor: {
      securityComplex: "SOR_019",
      energyConversionLab: "SOR_022",
      tarkintown: "SOR_025",
      jedhaCity: "SOR_028",
    },
    twi: {
      pauCity: "TWI_019",
      droidManufactory: "TWI_022",
      shadowCollectiveCamp: "TWI_025",
      petranakiArena: "TWI_028",
    },
    jtl: {
      colossus: "JTL_021",
      dataVault: "JTL_024",
      thermalOscillator: "JTL_025",
      nabatVillage: "JTL_028",
      lakeCountry: "JTL_031",
    },
    lof: {
      vergenceTemple: "LOF_019",
      mysticMonastery: "LOF_022",
      templeOfDestruction: "LOF_025",
      tombOfEilram: "LOF_028",
      // Common "Force" bases — "When a friendly Force unit attacks: create your Force token."
      nightsisterLair: "LOF_020",
      shadowedUndercity: "LOF_021",
      jediTemple: "LOF_023",
      starlightTemple: "LOF_024",
      fortressVader: "LOF_026",
      strangledCliffs: "LOF_027",
      crystalCaves: "LOF_029",
      theHolyCity: "LOF_030",
    },
    law: {
      allianceOutpost: "LAW_019",
      greatPitOfCarkoon: "LAW_023",
      shipbreakingYard: "LAW_026",
      citadelResearchCenter: "LAW_029",
      // Common "splash" bases — "Epic Action: Play a card from your hand, ignoring 1 of its
      // Vigilance, Command, Aggression, or Cunning aspect penalties."
      daimyosPalace: "LAW_020",
      coaxiumMine: "LAW_021",
      aldhaniGarrison: "LAW_022",
      imperialCommandComplex: "LAW_024",
      contestedCaverns: "LAW_025",
      stygeonSpire: "LAW_027",
      cantoBight: "LAW_028",
      partisanHideout: "LAW_030",
    }
  },
  leaders: {
    sor: {
      directorKrennic: "SOR_001",
      idenVersio: "SOR_002",
      chewbacca: "SOR_003",
      chirrutImwe: "SOR_004",
      lukeSkywalker: "SOR_005",
      emperorPalpatine: "SOR_006",
      grandMoffTarkin: "SOR_007",
      heraSyndulla: "SOR_008",
      leiaOrgana: "SOR_009",
      darthVader: "SOR_010",
      grandInquisitor: "SOR_011",
      ig88: "SOR_012",
      cassianAndor: "SOR_013",
      sabineWren: "SOR_014",
      bobaFett: "SOR_015",
      grandAdmiralThrawn: "SOR_016",
      hanSolo: "SOR_017",
      jynErso: "SOR_018",
    },
    shd: {
      garSaxon: "SHD_001",
      qira: "SHD_002",
      finn: "SHD_003",
      rey: "SHD_004",
      hondoOhnaka: "SHD_005",
      jabbaTheHutt: "SHD_006",
      moffGideon: "SHD_007",
      bobaFett: "SHD_008",
      hunter: "SHD_009",
      bossk: "SHD_010",
      kyloRen: "SHD_011",
      boKatanKryze: "SHD_012",
      hanSolo: "SHD_013",
      cadBane: "SHD_014",
      doctorAphra: "SHD_015",
      fennecShand: "SHD_016",
      landoCalrissian: "SHD_017",
      theMandalorian: "SHD_018",
    },
    twi: {
      nalaSe: "TWI_001",
      nuteGunray: "TWI_002",
      obiWanKenobi: "TWI_003",
      yoda: "TWI_004",
      countDooku: "TWI_005",
      watTambor: "TWI_006",
      captainRex: "TWI_007",
      padmeAmidala: "TWI_008",
      maul: "TWI_009",
      preVizsla: "TWI_010",
      ahsokaTano: "TWI_011",
      anakinSkywalker: "TWI_012",
      maceWindu: "TWI_013",
      asajjVentress: "TWI_014",
      generalGrievous: "TWI_015",
      jangoFett: "TWI_016",
      chancellorPalpatine: "TWI_017",
      quinlanVos: "TWI_018",
    },
    jtl: {
      asajjVentress: "JTL_001",
      grandAdmiralThrawn: "JTL_002",
      landoCalrissian: "JTL_003",
      roseTico: "JTL_004",
      admiralPiett: "JTL_005",
      darthVader: "JTL_006",
      admiralHoldo: "JTL_007",
      wedgeAntilles: "JTL_008",
      bobaFett: "JTL_009",
      captainPhasma: "JTL_010",
      majorVonreg: "JTL_011",
      lukeSkywalker: "JTL_012",
      poeDameron: "JTL_013",
      admiralTrench: "JTL_014",
      rioDurant: "JTL_015",
      admiralAckbar: "JTL_016",
      hanSolo: "JTL_017",
      kazudaXiono: "JTL_018",
    },
    lof: {
      kyloRen: "LOF_001",
      motherTalzin: "LOF_002",
      ahsokaTano: "LOF_003",
      kananJarrus: "LOF_004",
      morganElsbeth: "LOF_005",
      supremeLeaderSnoke: "LOF_006",
      avarKriss: "LOF_007",
      obiWanKenobi: "LOF_008",
      darthMaul: "LOF_009",
      thirdSister: "LOF_010",
      kitFisto: "LOF_011",
      rey: "LOF_012",
      barrissOffee: "LOF_013",
      grandInquisitor: "LOF_014",
      calKestis: "LOF_015",
      quiGonJinn: "LOF_016",
      darthRevan: "LOF_017",
      anakinSkywalker: "LOF_018",
    },
    law: {
      sawGerrera: "LAW_001",
      tobiasBeckett: "LAW_002",
      agentKallus: "LAW_003",
      aurraSing: "LAW_004",
      jynErso: "LAW_005",
      velSartha: "LAW_006",
      bobaFett: "LAW_007",
      directorKrennic: "LAW_008",
      heraSyndulla: "LAW_009",
      leiaOrgana: "LAW_010",
      darthVader: "LAW_011",
      sebulba: "LAW_012",
      chewbacca: "LAW_013",
      enfysNest: "LAW_014",
      jabbaTheHutt: "LAW_015",
      theClient: "LAW_016",
      hanSolo: "LAW_017",
      landoCalrissian: "LAW_018",
    },
    sec: {
      chancellorPalpatine: "SEC_001",
      jabbaTheHutt: "SEC_002",
      lamaSu: "SEC_003",
      leiaOrgana: "SEC_004",
      satineKryze: "SEC_005",
      colonelYularen: "SEC_006",
      drydenVos: "SEC_007",
      bailOrgana: "SEC_008",
      monMothma: "SEC_009",
      dedraMeero: "SEC_010",
      governorPryce: "SEC_011",
      cassianAndor: "SEC_012",
      luthenRael: "SEC_013",
      slyMoore: "SEC_014",
      c3po: "SEC_015",
      padmeAmidala: "SEC_016",
      sabe: "SEC_017",
      dj: "SEC_018",
    },
    ibh: {
      leiaOrgana: "IBH_001",
      darthVader: "IBH_053",
    },
    ash: {
      ahsokaTano: "ASH_009",
      theMandalorian: "ASH_014",
      grandAdmiralThrawn: "ASH_004",
    },
    ts26: {
      countDooku: "TS26_001",
      anakinSkywalker: "TS26_002",
      maul: "TS26_003",
      padmeAmidala: "TS26_004",
      savageOpress: "TS26_005",
      rex: "TS26_006",
      asajjVentress: "TS26_007",
      ahsokaTano: "TS26_008",
    },
  },
  units: {
    token: {
      battleDroid: "TWI_T01",
      cloneTrooper: "TWI_T02",
      tieFighter: "JTL_T01",
      xWing: "JTL_T02",
      spy: "SEC_T01",
      mandalorian: "ASH_T01",
    },
    sor: {
      consularSecurityForce: "SOR_046", // 3/7 Ground, no abilities — a durable test defender
      infernoFour: "SOR_031",
      lieutenantChildsen: "SOR_035",
      gideonHask: "SOR_036",
      academyDefenseWalker: "SOR_037",
      countDooku: "SOR_038",
      yoda: "SOR_045",
      obiWanKenobi: "SOR_049",
      kananJarrus: "SOR_047",
      theGhost: "SOR_050",
      lukeSkywalker: "SOR_051",
      lomPyke: "SOR_068",
      darthVaderLeaderUnit: "SOR_087",
      devastator: "SOR_090",
      rogueSquadronSkirmisher: "SOR_101",
      seasonedShoretrooper: "SOR_081",
      grandMoffTarkinUnit: "SOR_084",
      blizzardAssaultAtAt: "SOR_088",
      allianceDispatcher: "SOR_093",
      escortSkiff: "SOR_114",
      maceWinduUnit: "SOR_149",
      admiralAckbarSor: "SOR_097",
      fifthBrother: "SOR_131",
      bailOrgana: "SOR_094",
      monMothmaUnit: "SOR_096",
      steadfastBattalion: "SOR_116",
      homesteadMilitia: "SOR_113",
      specForceSoldier: "SOR_140",
      guerillaAttackPod: "SOR_148",
      jedhaAgitator: "SOR_158",
      bountyHunterCrew: "SOR_183",
      landoCalrissianUnit: "SOR_197",
      outerRimHeadhunter: "SOR_208",
      piratedStarfighter: "SOR_209",
      snowspeeder: "SOR_244",
      ninetySeventhLegion: "SOR_118",
      reinforcementWalker: "SOR_119",
      wingLeader: "SOR_241",
      systemPatrolCraft: "SOR_066",
      jabbaTheHutt: "SOR_181",
      chopper: "SOR_188",
      lothalInsurgent: "SOR_190",
      battlefieldMarine: "SOR_095",
      vigilantHonorGuards: "SOR_048",
      tieLnFighter: "SOR_225",
      echoBaseDefender: "SOR_098",
      brightHope: "SOR_099",
      homeOne: "SOR_102",
      superlaserTechnician: "SOR_083",
      admiralMotti: "SOR_226",
      zebOrrelios: "SOR_146",
      blackOne: "SOR_147",
      ardentSympathizer: "SOR_161",
      cartelSpacer: "SOR_178",
      bobaFettDisintegrator: "SOR_179",
      vanguardAce: "SOR_191",
      generalVeers: "SOR_230",
      tieAdvanced: "SOR_231",
      generalDodonna: "SOR_242",
      fightersForFreedom: "SOR_143",
      k2so: "SOR_145",
      wampa: "SOR_164",
      chewbaccaLoyalCompanion: "SOR_196",
      greedo: "SOR_204",
      craftySmuggler: "SOR_207",
      syndicateLackeys: "SOR_213",
      rebelPathfinder: "SOR_239",
      gamorreanGuards: "SOR_211",
      emperorPalpatine: "SOR_135",
      vanguardInfantry: "SOR_108",
      generalKrell: "SOR_105",
      generalTagge: "SOR_080",
      deathTrooper: "SOR_033",
      deathStarStormtrooper: "SOR_128",
      delMeeko: "SOR_034",
      darthVader: "SOR_087",
      cellBlockGuard: "SOR_229",
      atAtSuppressor: "SOR_039",
      surgicalDroid: "SOR_059",
      redemption: "SOR_052",
      avenger: "SOR_040",
      distantPatroller: "SOR_060",
      guardianOfTheWhills: "SOR_061",
      regionalGovernor: "SOR_062",
      patrollingVWing: "SOR_111",
      imperialInterceptor: "SOR_132",
      ruthlessRaider: "SOR_134",
      starWingScout: "SOR_163",
      leiaOrgana: "SOR_189",
      cantinaBouncer: "SOR_202",
      miningGuildTIE: "SOR_206",
      fleetLieutenant: "SOR_240",
      r2d2: "SOR_236",
      viperProbeDroid: "SOR_228",
      bodhiRook: "SOR_201",
      colonelYularen: "SOR_109",
      frontlineShuttle: "SOR_110",
      admiralOzzel: "SOR_129",
      explosivesArtist: "SOR_142",
      relentless: "SOR_089",
      sawGerrera: "SOR_153",
      ezraBridger: "SOR_192",
      millenniumFalconSor: "SOR_193",
      strafingGunship: "SOR_212",
      bendu: "SOR_056",
      ruggedSurvivors: "SOR_067",
      rukh: "SOR_085",
      gladiatorStarDestroyer: "SOR_086",
      wedgeAntillesSor: "SOR_100",
      seventhSister: "SOR_133",
    },
    shd: {
      superlaserTechnician: "SHD_085",
      rhokaiGunship: "SHD_164",
      bazineNetal: "SHD_184",
      l337: "SHD_197",
      ruthlessAssassin: "SHD_235",
      concordDawnInterceptors: "SHD_042",
      doctorPershing: "SHD_028",
      lurkingTiePhantom: "SHD_187",
      generalTagge: "SHD_081",
      sundariPeaceKeeper: "SHD_098",
      recklessGunslinger: "SHD_160",
      fourLom: "SHD_188",
      zuckuss: "SHD_190",
      hylobonEnforcer: "SHD_027",
      dengar: "SHD_133",
      tech: "SHD_248",
      warbirdStowaway: "SHD_086",
      chewbaccaPykesbane: "SHD_050",
      sugi: "SHD_052",
      djBlatantThief: "SHD_213",
      theMandalorian: "SHD_049",
      tobiasBeckett: "SHD_217",
      supercommandoSquad: "SHD_034",
      followerOfTheWay: "SHD_056",
      ketsuOnyo: "SHD_147",
      kraytDragon: "SHD_172",
    },
    jtl: {
      redLeader: "JTL_101",
      kijimiPatrollers: "JTL_082",
      mistHunter: "JTL_186",
      hondoOhnaka: "JTL_056",
      l337: "JTL_049",
      warJuggernaut: "JTL_170",
      ig2000: "JTL_140",
      lukeSkywalker: "JTL_094",
      blueLeader: "JTL_096",
      rebelliousHammerhead: "JTL_153",
      snapWexley: "JTL_098",
      r2d2: "JTL_245",
      millenniumFalcon: "JTL_249",
      theMandalorianPilot: "JTL_210",
      shuttleSt149: "JTL_242",
      redFive: "JTL_151",
      devastator: "JTL_143",
      onyxSquadronBrute: "JTL_033",
      chimaera: "JTL_039",
      desperateCommando: "JTL_060",
      anakinSkywalker: "JTL_197",
      blackOne: "JTL_147",
      poeDameron: "JTL_100",
      raddus: "JTL_104",
      resistanceBlueSquadron: "JTL_102",
      resistanceXWing: "JTL_247",
      dilapidatedSkiSpeeder: "JTL_248",
    },
    lof: {
      kelleranBeq: "LOF_100",
      hyperspaceWayfarer: "LOF_119", // 4/10 Space, no abilities — a durable test defender
      grogu: "LOF_246",
      gungi: "LOF_093",
      babuFrik: "LOF_206",
      nightsisterWarrior: "LOF_059",
      hk47: "LOF_130",
      darthVader: "LOF_037",
      priestessesOfTheForce: "LOF_072",
      strikeship: "LOF_131",
      witchOfTheMist: "LOF_154",
      theLegacyRun: "LOF_213",
      sandtrooperCavalry: "LOF_232",
      vanee: "LOF_082",
      darthTyranus: "LOF_231",
      itinerantWarrior: "LOF_048",
      yaddle: "LOF_045",
      theFather: "LOF_260",
      oggdoBogdo: "LOF_063",
      guardianOfTheWhills: "LOF_058",
      karis: "LOF_031",
      anakinSkywalkerChampionOfMortis: "LOF_070",
      hyenaBomber: "LOF_158",
      lukeSkywalker: "LOF_249", // A Hero's Beginning — 3/5 Ground, unique
    },
    twi: {
      infiltratingDemolisher: "TWI_182",
      shaakTi: "TWI_094",
      anakinsInterceptor: "TWI_142",
      admiralTrench: "TWI_086",
      sanHill: "TWI_186",
      r2d2FullOfSolutions: "TWI_193",
      battleDroidEscort: "TWI_229",
      cloneHeavyGunner: "TWI_158",
      separatistCommando: "TWI_180",
      confederateCourier: "TWI_079",
      hailfireTank: "TWI_233",
      subjugatingStarfighter: "TWI_112",
      confederateTriFighter: "TWI_132",
    },
    sec: {
      cadBane: "SEC_034",
      unrulyAstromech: "SEC_221",
      huntingAssassinDroid: "SEC_134",
      chancellorPalpatine: "SEC_082",
      isbShuttle: "SEC_083",
      viceAdmiralRampart: "SEC_085",
      nalaSe: "SEC_065",
      gnkPowerDroid: "SEC_110",
      outerRimConstable: "SEC_163",
      darthTraya: "SEC_188",
      karisNemik: "SEC_148",
      grandAdmiralThrawn: "SEC_193",
    },
    law: {
      imperialDoorTechnician: "LAW_097",
      scavengingSandcrawler: "LAW_238",
      bt1: "LAW_173",
      tripleZero: "LAW_174",
      k2so: "LAW_079",
      galenErso: "LAW_233",
      zebOrellios: "LAW_045",
      chioFain: "LAW_048",
      honnah: "LAW_050",
      ig88: "LAW_042",
      lawbringer: "LAW_101",
      expendableMercenary: "LAW_159",
      sabineWren: "LAW_078",
      shieldedHauler: "LAW_122",
      ohnakaGangBandits: "LAW_199",
      vigilantScouts: "LAW_120",
      guildAmbushTeam: "LAW_239",
    },
    ash: {
      antDroid: "ASH_116",
      ravager: "ASH_102",
      poeDameron: "ASH_040",
      moffGideonRemnantCommander: "ASH_097",
      helgait: "ASH_195",
      praetorianElite: "ASH_145",
      outlandProtector: "ASH_117",
      fangFighterSquadron: "ASH_130",
      flankingTieInterceptor: "ASH_215",
      mosEisleyModifier: "ASH_074",
      remnantInterceptor: "ASH_095",
      blurrg: "ASH_121",
      honorableNiteOwl: "ASH_154",
      unsanctionedPatrol: "ASH_222",
      marroksFiendFighter: "ASH_241",
      domesticatedLothCat: "ASH_068",
      emperorsMessenger: "ASH_189",
      doctorPershing: "ASH_072",
      leiaOrgana: "ASH_059",
      gozantiAssaultCarrier: "ASH_099",
      r5d4: "ASH_156",
      migsMayfeld: "ASH_168",
      mandosN1Starfighter: "ASH_203",
      ezraBridger: "ASH_209",
      yellowAcesBomber: "ASH_253",
      scionShuttle: "ASH_046",
      carsonTeva: "ASH_202",
      grandAdmiralThrawn: "ASH_033",
      rukh: "ASH_036",
      redLeader: "ASH_037",
      morganElsbeth: "ASH_050",
      theGreatMothers: "ASH_101",
      halo: "ASH_223",
      snubFighterSquadron: "ASH_194",
      marrok: "ASH_030",
      rancorKeeper: "ASH_032",
      coronaFour: "ASH_043",
      huyang: "ASH_056",
      atAttinSafetyDroid: "ASH_070",
      summaVerminoth: "ASH_083",
      ferryDroid: "ASH_218",
      boKatanKryze: "ASH_105",
      t6Shuttle1974: "ASH_109",
      lukeSkywalker: "ASH_112",
      warriorOfClanKryze: "ASH_120",
      protectorateFighter: "ASH_124",
      queenSoruna: "ASH_132",
      mortarTrooper: "ASH_142",
      vanesSnubFighter: "ASH_144",
      justifier: "ASH_146",
      theCyborgMech: "ASH_147",
      eviscerator: "ASH_149",
      greenLeader: "ASH_153",
      dangerSquadronWingmen: "ASH_157",
      hanSolo: "ASH_158",
      clanVizslaSoldier: "ASH_165",
      flarestarAttackShuttle: "ASH_167",
      desertSharpshooter: "ASH_170",
      pegasusTriWing: "ASH_171",
      razorCrest: "ASH_172",
      starfortressHeavyBomber: "ASH_174",
      inspiringVeteran: "ASH_205",
      imposingScoutWalker: "ASH_176",
      executor: "ASH_197",
      shinHatisFiendFighter: "ASH_191",
      bladeThree: "ASH_204",
      bobaFettsRancor: "ASH_179",
      gorianShardsCorsair: "ASH_196",
      kelleranBeq: "ASH_206",
      heroicPurrgil: "ASH_207",
      sabineWren: "ASH_208",
      mandalorianScout: "ASH_216",
      remnantLookouts: "ASH_220",
      qira: "ASH_226",
      mouseDroid: "ASH_237",
      attendantNavigator: "ASH_238",
      mandalorianSuperCommandos: "ASH_240",
      darthVader: "ASH_243",
      neel: "ASH_248",
      zealousSoldier: "ASH_251",
      gallofreeTransport: "ASH_254",
      lepRatcatcher: "ASH_259",
      // Leader units (the deployed side of the ASH leaders)
      ahsokaTano: "ASH_009",
      theMandalorian: "ASH_014",
    },
    ts26: {
      deployedDroideka: "TS26_077",
    },
    ibh: {
      // Each card has multiple identical printings within IBH; suffix letters are alternate printings.
      chewbacca: "IBH_003", chewbaccaB: "IBH_046",
      rogueSquadronSpeeder: "IBH_004", rogueSquadronSpeederB: "IBH_017", rogueSquadronSpeederC: "IBH_034",
      rebellionYWing: "IBH_006", rebellionYWingB: "IBH_024", rebellionYWingC: "IBH_032",
      brightHope: "IBH_014", brightHopeB: "IBH_026",
      ionCannon: "IBH_016", ionCannonB: "IBH_027",
      generalRieekan: "IBH_023", generalRieekanB: "IBH_036",
      hanSolo: "IBH_010", hanSoloB: "IBH_042",
      admiralPiett: "IBH_060", admiralPiettB: "IBH_065",
      hothLieutenant: "IBH_064", hothLieutenantB: "IBH_092",
      imperialDeckOfficer: "IBH_062", imperialDeckOfficerB: "IBH_100",
      ewebGunner: "IBH_069", ewebGunnerB: "IBH_083",
      blizzardForceAtst: "IBH_070", blizzardForceAtstB: "IBH_089", blizzardForceAtstC: "IBH_103",
      deathSquadronStarDestroyer: "IBH_079", deathSquadronStarDestroyerB: "IBH_098",
      lambdaShuttle: "IBH_058", lambdaShuttleB: "IBH_084", lambdaShuttleC: "IBH_090",
      generalVeers: "IBH_068", generalVeersB: "IBH_088",
      surfaceAssaultBomber: "IBH_078", surfaceAssaultBomberB: "IBH_093", surfaceAssaultBomberC: "IBH_094",
      blizzardOne: "IBH_099",
    },
  },
  upgrades: {
    token: {
      experience: "SOR_T01",
      shield: "SOR_T02",
      advantage: "ASH_T02",
    },
    sor: {
      entrenched: "SOR_072",
      protector: "SOR_057",
      academyTraining: "SOR_120",
      traitorous: "SOR_122",
      hardpointHeavyBlaster: "SOR_121",
      smugglingCompartment: "SOR_214",
      lukesLightsaber: "SOR_053",
      vadersLightsaber: "SOR_136",
      jediLightsaber: "SOR_054",
      electrostaff: "SOR_071",
      fallenLightsaber: "SOR_137",
    },
    shd: {
      legalAuthority: "SHD_124",
      publicEnemy: "SHD_068",
      imprisoned: "SHD_072",
      hotshotBlaster: "SHD_174",
      theDarksaber: "SHD_126",
      mandalorianArmor: "SHD_073",
      vambraceFlamethrower: "SHD_177",
      frozenInCarbonite: "SHD_193",
      wanted: "SHD_221",
    },
    jtl: {
      jarekYeager: "JTL_109",
    },
    lof: {
      bolsteredEndurance: "LOF_074",
      constructedLightsaber: "LOF_261",
      sizeMattersNot: "LOF_056",
      cravingPower: "LOF_091",
    },
    ash: {
      camtono: "ASH_229",
      nowhereToHide: "ASH_198",
      whistlingBirds: "ASH_183",
      bladeOfTalzin: "ASH_055",
      durasteelPlating: "ASH_086",
      cyberneticEnhancements: "ASH_087",
      deadlyVulnerability: "ASH_150",
      bokkenSaber: "ASH_180",
      markMyWords: "ASH_181",
      unfetteredAmbition: "ASH_182",
      preparation: "ASH_228",
      faithInTheEmpire: "ASH_262",
      theWayOfTheMandalor: "ASH_263",
    },
    twi: {
      unshakeableWill: "TWI_071",
    },
    sec: {
      clandestineConnections: "SEC_264",
      disciplesDevotion: "SEC_071",
    },
  },
  events: {
    shd: {
      timelyIntervention: "SHD_129",
      chooseSides: "SHD_132",
      midnightRepairs: "SHD_054",
      daringRaid: "SHD_178",
      pillage: "SHD_181",
      maKlounkee: "SHD_229",
    },
    sor: {
      searchYourFeelings: "SOR_042",
      theForceIsWithMe: "SOR_055",
      emperorsLegion: "SOR_091",
      itBindsAllThings: "SOR_075",
      superlaserBlast: "SOR_043",
      repair: "SOR_074",
      powerOfTheDarkSide: "SOR_041",
      momentOfPeace: "SOR_073",
      rebelAssault: "SOR_103",
      strikeTrue: "SOR_127",
      forceChoke: "SOR_139",
      rallyingCry: "SOR_154",
      resupply: "SOR_126",
      prepareForTakeoff: "SOR_125",
      asteroidSanctuary: "SOR_218",
      medalCeremony: "SOR_245",
      heroicSacrifice: "SOR_150",
      waylay: "SOR_222",
      changeOfHeart: "SOR_224",
      confiscate: "SOR_251",
      attackPatternDelta: "SOR_106",
      takedown: "SOR_077",
      overwhelmingBarrage: "SOR_092",
      vanquish: "SOR_078",
      recruit: "SOR_123",
      uWingReinforcement: "SOR_104",
      makeAnOpening: "SOR_076",
      tacticalAdvantage: "SOR_124",
      karabast: "SOR_151",
      forACauseIBelieveIn: "SOR_152",
      iHadNoChoice: "SOR_187",
      iAmYourFather: "SOR_233",
      maximumFirepower: "SOR_234",
      galacticAmbition: "SOR_235",
      shootFirst: "SOR_217",
      dontGetCocky: "SOR_223",
      keepFighting: "SOR_169",
      powerFailure: "SOR_170",
      missionBriefing: "SOR_171",
      openFire: "SOR_172",
      bombingRun: "SOR_173",
      disarm: "SOR_216",
      surpriseStrike: "SOR_220",
      outmaneuver: "SOR_221",
      sparkOfRebellion: "SOR_200",
      forceThrow: "SOR_167",
      smokeAndCinders: "SOR_174",
      forcedSurrender: "SOR_175",
      noGoodToMeDead: "SOR_186",
      bamboozle: "SOR_199",
      vigilance: "SOR_058",
      command: "SOR_107",
      aggression: "SOR_155",
      cunning: "SOR_203",
    },
    twi: {
      christophsis: "TWI_078",
      vanquish: "TWI_077",
      waylay: "TWI_226", // reprint of SOR_222
      droidDeployment: "TWI_237",
      dropIn: "TWI_251",
      takeCaptive: "TWI_128",
      daringRaid: "TWI_170",
      unnaturalLife: "TWI_189",
      breakingIn: "TWI_224",
    },
    jtl: {
      repair: "JTL_075",
      stayOnTarget: "JTL_177",
      trenchRun: "JTL_156",
      torpedoBarrage: "JTL_234",
      dedicatedWingmen: "JTL_254",
      unityOfPurpose: "JTL_106",
      flyCasual: "JTL_206",
      noGloryOnlyResults: "JTL_043",
      punchIt: "JTL_231",
      attackRun: "JTL_261",
    },
    ts26: {
      backedByThePykes: "TS26_058",
    },
    sec: {
      iAmTheSenate: "SEC_092",
      grassrootsResistance: "SEC_258",
    },
    ash: {
      // Identical reprint of SEC_258 Grassroots Resistance.
      grassrootsResistance: "ASH_258",
      galvanizedLeap: "ASH_188",
      strongerTogether: "ASH_140",
      foundlingRescue: "ASH_092",
      wipeThemOut: "ASH_137",
      holdThemOff: "ASH_139",
      studentGuidesTheMaster: "ASH_115",
      longLiveTheEmpire: "ASH_103",
      operationCinder: "ASH_151",
      recklessSacrifice: "ASH_163",
      followMe: "ASH_184",
      treacherousMinefield: "ASH_186",
      reckoning: "ASH_187",
      rehabilitation: "ASH_200",
      fatefulGoodbye: "ASH_211",
      diplomaticPageantry: "ASH_231",
      fullOfSurprises: "ASH_232",
      masterstroke: "ASH_234",
      senseThroughTheForce: "ASH_235",
      farFarAway: "ASH_236",
      oneMustDestroyToCreate: "ASH_247",
      chooseYourPath: "ASH_257",
    },
    law: {
      unmarkedCredits: "LAW_244",
      backedByTheHutts: "LAW_247",
      haymaker: "LAW_168",
      lostAndForgotten: "LAW_133",
      singleReactorIgnition: "LAW_044",
      doubleCross: "LAW_170",
    },
    lof: {
      cureWounds: "LOF_075",
      sorcerousBlast: "LOF_172",
      shatterpoint: "LOF_079",
      protectThePod: "LOF_128",
      shienFlurry: "LOF_220",
    },
    ibh: {
      // Suffix letters are alternate identical printings within IBH.
      theDesolationOfHoth: "IBH_104",
      youHaveFailedMe: "IBH_095",
      tooStrongForBlasters: "IBH_066", tooStrongForBlastersB: "IBH_091",
      wereInTrouble: "IBH_061", wereInTroubleB: "IBH_086",
      targetTheMainGenerator: "IBH_059", targetTheMainGeneratorB: "IBH_071",
      illCoverForYou: "IBH_005", illCoverForYouB: "IBH_039",
      improvisedDetonation: "IBH_021", improvisedDetonationB: "IBH_030",
    },
  },
}
