import { GameStateBuilder } from "@/server/puzzle/game-state-builder";

export const sabineWrenCadBaneSimplePuzzleState = new GameStateBuilder()
  .WithActivePlayer(1)
  .WithGamePhase(0)
  .MyBase("SOR_022", 23)
  .MyLeader("SOR_014")
  .TheirBase("SOR_025", 11)
  .TheirLeader("SHD_014", true, false, true)
  .FillResourcesForPlayer(1, "SHD_160", 8)
  .WithCardInHandForPlayer(1, "JTL_153")
  .WithCardInHandForPlayer(1, "SOR_168")
  .WithCardInHandForPlayer(1, "SOR_103")
  .WithCardInHandForPlayer(1, "SOR_141")
  .WithCardInHandForPlayer(1, "SOR_150")
  .WithGroundUnitForPlayer(1, "SOR_145")
  .WithGroundUnitForPlayer(1, "SHD_160")
  .WithGroundUnitForPlayer(2, "SOR_211", false)
  .WithGroundUnitForPlayer(2, "TWI_187", false)
  .WithCurrentRoundBeing(7)
  .WithInitiativePlayerBeing(2)
  .WithInitiativeClaimed()
  .Build()
;
