import type {
  Base,
  Card,
  CurrentEffect,
  DiscardedCard,
  GamePhase,
  Leader,
  PlayerId,
  Resource,
  Unit,
} from "@/lib/engine/core-models";
import type { TriggerEntry } from "@/lib/engine/trigger-types";

/** How a card entered play this phase. */
export type EntryReason =
  | "played"            // paid cost from hand
  | "deployed"          // leader flipped from Leader zone
  | "returned-to-play"  // bounced back, resurrected, or similar
  | "token-created"     // token unit generated by an ability
  | "other";

/** How a card left play this phase. */
export type ExitReason =
  | "defeated"          // HP reached 0 or "defeat" effect
  | "captured"          // taken captive by another unit (non-tokens only)
  | "token-defeated"    // captured token — tokens cannot be held captive
  | "returned-to-hand"  // bounce (e.g. "return to owner's hand")
  | "returned-to-deck"  // shuffled back into deck
  | "other";

export interface PlayerState {
  base: Base;
  leader: Leader;
  spaceArena: Unit[];
  groundArena: Unit[];
  resources: Resource[];
  discard: DiscardedCard[];
  deck: Card[];
  hand: Card[];
  supplemental: {
    forceToken?: boolean;
    creditTokens?: number;
  };
}

export interface GameState {
  activePlayer: PlayerId;
  defeatedPlayers: PlayerId[];
  gamePhase: GamePhase;
  nextPlayId: number;
  player1: PlayerState;
  player2: PlayerState;
  currentEffects: CurrentEffect[];
  currentRound: number;
  initiativePlayer: PlayerId;
  initiativeClaimed: boolean;
  roundState: {
    cardsPlayedThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string }[];
    cardsEnteredPlayThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string; reason: EntryReason }[];
    cardsLeftPlayThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string; reason: ExitReason }[];
    unitsAttackedThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string }[];
  };
  triggerBag: TriggerEntry[];
}

export interface Game {
  id: string;
  currentGameState: GameState;
  gameStateHistory: GameState[];
  gameLog: string[];
}
