import type {
  Base,
  Card,
  CurrentEffect,
  DiscardedCard,
  GamePhase,
  Leader,
  PlayerId,
  Resource,
  Unit,
} from "@/lib/engine/core-models";
import type { TriggerEntry } from "@/lib/engine/trigger-types";

/** How a card entered play this phase. */
export type EntryReason =
  | "played"            // paid cost from hand
  | "deployed"          // leader flipped from Leader zone
  | "returned-to-play"  // bounced back, resurrected, or similar
  | "token-created"     // token unit generated by an ability
  | "other";

/** How a card left play this phase. */
export type ExitReason =
  | "defeated"          // HP reached 0 or "defeat" effect
  | "captured"          // taken captive by another unit (non-tokens only)
  | "token-defeated"    // captured token — tokens cannot be held captive
  | "returned-to-hand"  // bounce (e.g. "return to owner's hand")
  | "returned-to-deck"  // shuffled back into deck
  | "other";

export interface PlayerState {
  base: Base;
  leader: Leader;
  spaceArena: Unit[];
  groundArena: Unit[];
  resources: Resource[];
  discard: DiscardedCard[];
  deck: Card[];
  hand: Card[];
  supplemental: {
    forceToken?: boolean;
    creditTokens?: number;
  };
}

export interface GameState {
  activePlayer: PlayerId;
  defeatedPlayers: PlayerId[];
  gamePhase: GamePhase;
  nextPlayId: number;
  player1: PlayerState;
  player2: PlayerState;
  currentEffects: CurrentEffect[];
  currentRound: number;
  initiativePlayer: PlayerId;
  initiativeClaimed: boolean;
  roundState: {
    cardsPlayedThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string }[];
    cardsPlayedThisRound: { fromPlayer: PlayerId; cardId: string; playId: string; playedAs: "Unit" | "Upgrade" | "Event" | "Pilot" }[];
    cardsEnteredPlayThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string; reason: EntryReason }[];
    cardsLeftPlayThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string; reason: ExitReason }[];
    unitsAttackedThisPhase: { fromPlayer: PlayerId; cardId: string; playId: string; }[];
    baseDamagedThisPhase: { byPlayer: PlayerId; target: PlayerId }[];
    /** playIds of units that took damage this phase (e.g. ASH_188 Galvanized Leap). */
    unitsDamagedThisPhase: string[];
    lastActionWasPass: boolean;
    regroupResourcedPlayers: PlayerId[];
    /** Number of times either player has Used the Force this phase (e.g. LOF_007 Avar Kriss). */
    forceUsedThisPhase: number;
    /**
     * "Take an extra action after this one" (e.g. JTL_018 Kazuda Xiono) — the player who keeps
     * priority instead of passing the turn. Consumed by the next advanceTurn.
     */
    extraActionPlayer?: PlayerId;
  };
  triggerBag: TriggerEntry[];
  /**
   * CR 7.6.10 — when triggers from both players wait simultaneously, the active player picks
   * which player's stack resolves first. This holds the chosen player while their stack drains,
   * so the other player's triggers are deferred (and no re-prompt occurs). Cleared once that
   * player's triggers are exhausted.
   */
  triggerBatchPlayer?: PlayerId;
}

export interface Game {
  id: string;
  currentGameState: GameState;
  gameStateHistory: GameState[];
  gameLog: string[];
}
